# REUSE licensing information (REUSE Specification 3.0).
#
# Source files carry `SPDX-License-Identifier` in their own header. The copyright notice and the
# licence for every file are declared here instead of in 60+ per-file headers, so there is exactly
# one authoritative statement of who holds the copyright — this file and LICENSE-MIT.
version = 1

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019-present Trade"
SPDX-License-Identifier = "MIT OR Apache-2.0"
